# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.str_splitC <- function(str, sep) {
    .Call(`_varkitExtra_str_split`, str, sep)
}

.index_vcfC <- function(x) {
    .Call(`_varkitExtra_index_vcf`, x)
}

